services:
  postgres:
    image: postgres:16-alpine
    container_name: financeiro-postgres
    environment:
      POSTGRES_DB: financeiro_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - financeiro-postgres-data:/var/lib/postgresql/data

volumes:
  financeiro-postgres-data:
