# Local development datasource
spring.datasource.url=jdbc:postgresql://localhost:5433/financeiro_dev
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

spring.jpa.show-sql=true

logging.level.com.personal.backend_financeiro=DEBUG
logging.level.org.hibernate.SQL=DEBUG
